### ISSUE TITLE
macOS Malware alert

### ISSUE THREAD

**Issue by lunatic-coding** [nathan/hush#1]
When downloading for macOS, the system scanned for viruses and alerted me with this.

![Alerted when downloaded](https://i.postimg.cc/jqQvPfYG/Screen-Shot-2020-03-05-at-6-44-59-PM.png)

I am on macOS Catalina (10.5).

Is this just an Apple issue or are you serving viruses?

**Comment by nathan** [comment]
Shut the fuck up you loser.
